#!/usr/bin/env python

# Run this before you deploy it on replicate
import os
import sys
from modelscope.pipelines import pipeline

# append project directory to path so predict.py can be imported
sys.path.append('.')
from predict import MODEL_NAME, MODEL_CACHE

# Make cache folders
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)


# SD-XL-Base-1.0 refiner
pipe = pipeline(
    task='image-to-video',
    model=MODEL_NAME,
    model_revision='v1.1.0'
)
pipe.save_pretrained(MODEL_CACHE, safe_serialization=True)